### ISSUE TITLE
No error message for duplicate labels

### ISSUE THREAD

**Issue by VegarRingdalAibel** [AibelDevs/action-toolbox#20]
it not allowing me to merge, so thats good.
But we are missing the pull request review section

![image](https://github.com/AibelDevs/action-toolbox/assets/94840334/7fa42c3c-fc00-48fe-b2d3-a2b1a003225c)

![image](https://github.com/AibelDevs/action-toolbox/assets/94840334/e58d987d-66a3-4c13-9149-79c8981e23fc)

**Comment by Krande** [comment]
Yup, this is pure laziness from me :)

I just threw in a exit code 1 on this, because I planned on fixing it later :)

https://github.com/AibelDevs/action-toolbox/blob/main/.github/workflows/tool-pr-version-calculate.yaml#L137-L141
